import React, { useState } from 'react';
import { ChevronDown, HelpCircle, MessageSquare } from 'lucide-react';
import { PRIMARY_STICKY_WHATSAPP } from '../data';
import { WhatsAppIcon } from './WhatsAppIcon';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

const FAQS: FAQItem[] = [
  {
    id: 'faq-role',
    question: 'What does a Sales Representative at EventsKonnectGH do?',
    answer:
      'As a Sales Representative, you reach out to local Ghanaian event vendors and service providers (such as caterers, photographers, videographers, DJs, MCs, decorators, makeup artists, and event venues), introduce them to EventsKonnectGH, and help them get registered and listed on our platform to reach more paying clients.'
  },
  {
    id: 'faq-earnings',
    question: 'How much do I earn and how am I paid?',
    answer:
      'You earn a 30% commission (15 GH₵) for every vendor who registers on EventsKonnectGH through your outreach. There is no earnings cap—for example, registering 5 vendors a day earns you 75 GH₵ daily (2,250 GH₵ monthly). Verified commissions are paid out promptly to your Mobile Money (MoMo) or bank account.'
  },
  {
    id: 'faq-time-commitment',
    question: 'What is the time commitment? Are there fixed working hours?',
    answer:
      'There are no mandatory shifts or fixed hours. You have complete flexibility to work at your own pace—part-time around your studies, full-time, or as a side hustle during your free time. Your earnings correspond directly to the effort and time you choose to invest.'
  },
  {
    id: 'faq-whatsapp',
    question: 'How does contacting you on WhatsApp work and what happens next?',
    answer:
      'Clicking any WhatsApp button connects you directly to our official recruitment team. We will greet you, answer any specific questions you have, and provide your registration instructions and vendor outreach materials so you can start introducing vendors right away.'
  },
  {
    id: 'faq-fees',
    question: 'Is there any fee to join as a Sales Representative?',
    answer:
      'No. Joining the EventsKonnectGH sales team is 100% free. We never ask for any registration fees, application payments, or upfront charges. You earn directly from the legitimate commissions generated by vendor registrations.'
  },
  {
    id: 'faq-requirements',
    question: 'Do I need prior sales experience or formal qualifications?',
    answer:
      'No formal background or sales degree is required. All you need is a smartphone with active internet access, good communication skills, confidence in speaking to business owners, and a self-motivated, honest work ethic.'
  }
];

export const FAQSection: React.FC = () => {
  const [openId, setOpenId] = useState<string | null>(FAQS[0].id);

  const toggleFAQ = (id: string) => {
    setOpenId((prev) => (prev === id ? null : id));
  };

  return (
    <section id="faq" className="py-14 sm:py-20 bg-white border-t border-slate-200">
      <div className="max-w-[900px] mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-10 sm:mb-14">
          <div className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-red-50 text-red-700 text-xs sm:text-sm font-bold uppercase tracking-wider mb-3">
            <HelpCircle className="w-4 h-4" />
            <span>Got Questions?</span>
          </div>
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold text-slate-950 tracking-tight mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-sm sm:text-base text-slate-600 leading-relaxed">
            Everything you need to know about the Sales Representative opportunity, commissions, and joining our team.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-3.5">
          {FAQS.map((faq) => {
            const isOpen = openId === faq.id;
            return (
              <div
                key={faq.id}
                className={`border rounded-xl transition-colors duration-200 overflow-hidden ${
                  isOpen
                    ? 'border-red-200 bg-red-50/20 shadow-xs'
                    : 'border-slate-200 bg-white hover:border-slate-300'
                }`}
              >
                <button
                  id={`faq-btn-${faq.id}`}
                  onClick={() => toggleFAQ(faq.id)}
                  aria-expanded={isOpen}
                  className="w-full text-left px-5 sm:px-6 py-4 sm:py-5 flex items-center justify-between gap-4 cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-red-500 rounded-xl"
                >
                  <span className="font-bold text-slate-900 text-base sm:text-lg leading-snug">
                    {faq.question}
                  </span>
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 transition-transform duration-200 ${
                      isOpen
                        ? 'bg-red-600 text-white rotate-180'
                        : 'bg-slate-100 text-slate-600'
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div
                    id={`faq-ans-${faq.id}`}
                    className="px-5 sm:px-6 pb-5 pt-1 text-sm sm:text-base text-slate-600 leading-relaxed border-t border-slate-100"
                  >
                    <p>{faq.answer}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Additional Questions CTA card */}
        <div className="mt-10 sm:mt-12 bg-slate-50 border border-slate-200 rounded-2xl p-6 sm:p-8 text-center max-w-xl mx-auto">
          <div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mx-auto mb-3">
            <MessageSquare className="w-5 h-5" />
          </div>
          <h3 className="text-base sm:text-lg font-bold text-slate-900 mb-1">
            Have a question that isn't answered here?
          </h3>
          <p className="text-xs sm:text-sm text-slate-600 mb-5">
            Our recruitment advisors are active on WhatsApp and ready to assist with any questions or clarifications.
          </p>
          <a
            id="faq-whatsapp-inquiry-btn"
            href={PRIMARY_STICKY_WHATSAPP}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center justify-center gap-2 bg-[#25D366] hover:bg-[#1ebd59] text-white text-sm sm:text-base font-bold px-5 py-2.5 rounded-xl shadow-xs transition-all active:scale-95"
          >
            <WhatsAppIcon className="w-4 h-4 fill-white text-white" />
            <span>Chat with Recruitment on WhatsApp</span>
          </a>
        </div>

      </div>
    </section>
  );
};
